### ISSUE TITLE
Documentation: additional bibliographic info on footnote 28

### ISSUE THREAD

**Issue by sls** [mazeppa-dev/mazeppa#19]
Hi, would you accept a PR to add ISBN 978-3-540-61580-4 and the link https://dl.acm.org/doi/proceedings/10.5555/647372 to footnote 28? If so I will be happy to add them in any format you may prefer.

**Comment by Hirrolot** [comment]
We have no single preferred citation format, but it seems that ISBNs are generally discouraged:

> ISBNs are not included in works-cited-list entries for a number of reasons. First, ISBNs were developed only in the second half of the twentieth century, so older books won’t have them. Second, an ISBN doesn’t help readers directly access the book’s content.

Source: https://style.mla.org/isbn-works-cited-list-entries/.

So let's just append the link https://dl.acm.org/doi/10.5555/647372.724040 to the end of the citation, as we do for some other citations currently. The PR would be much appreciated!
